import React, { useState } from 'react';
import { useParams, Link } from 'react-router-dom';
import { ArrowLeft, FileText, Clock, Users, CreditCard, MapPin, Building, Zap } from 'lucide-react';
import MarkdownSummary from '../components/MarkdownSummary';
import PaymentEvents from '../components/PaymentEvents';
import InfoSection from '../components/InfoSection';
import { getTransactionById } from '../data/mockData';

const TransactionDetails: React.FC = () => {
  const { id } = useParams<{ id: string }>();
  const transaction = getTransactionById(id || '');

  if (!transaction) {
    return (
      <div className="max-w-4xl mx-auto p-6">
        <div className="text-center py-12">
          <h2 className="text-2xl font-semibold text-gray-900 mb-4">Transaction Not Found</h2>
          <Link to="/" className="text-blue-600 hover:text-blue-700">
            ← Back to Results
          </Link>
        </div>
      </div>
    );
  }

  const aiSummary = `# Transaction Analysis Report

## Overview
This high-value transaction of **₹${transaction.amount.toLocaleString()}** represents a significant fund transfer between commercial entities. The transaction was processed through our secure payment gateway with enhanced verification protocols.

## Key Insights
- **Risk Assessment**: Low risk based on sender's transaction history and KYC compliance
- **Processing Time**: Completed within standard timeframe of 2.3 seconds
- **Verification**: All regulatory checks passed successfully
- **Geographic Analysis**: Standard domestic transfer within approved corridors

## Compliance Notes
✅ AML screening completed  
✅ Sanctions list verification passed  
✅ Transaction limits validated  
✅ Beneficiary verification successful

*Generated by AI Banking Intelligence System*`;

  const paymentEvents = [
    { stage: 'Initiated', timestamp: '2024-05-15 14:23:45 IST', status: 'completed' },
    { stage: 'Validated', timestamp: '2024-05-15 14:23:47 IST', status: 'completed' },
    { stage: 'Authorized', timestamp: '2024-05-15 14:23:48 IST', status: 'completed' },
    { stage: 'Settled', timestamp: '2024-05-15 14:23:50 IST', status: 'completed' },
  ];

  const paymentPartyInfo = {
    'Sender Name': 'Tech Solutions Pvt Ltd',
    'Sender Account': '9876543210123456',
    'Sender IFSC': 'HDFC0001234',
    'Sender Type': 'Corporate',
    'Sender Location': 'Mumbai, Maharashtra',
    'Beneficiary Name': 'Global Enterprises Ltd',
    'Beneficiary Account': '1234567890654321',
    'Beneficiary IFSC': 'ICIC0005678',
    'Beneficiary Type': 'Corporate',
    'Beneficiary Location': 'Delhi, NCR',
    'Relationship': 'Vendor Payment',
    'Purpose Code': 'S0101',
  };

  const remittanceInfo = {
    'Transaction Type': 'NEFT',
    'Channel': 'Internet Banking',
    'Reference Number': 'TXN2024051500123',
    'UTR Number': 'HDFC24135N240515001',
    'Charges': '₹5.90',
    'Exchange Rate': 'N/A',
    'Instruction Priority': 'Normal',
    'Value Date': '2024-05-15',
    'Booking Date': '2024-05-15',
  };

  const riskInfo = {
    'Risk Score': '2.3/10 (Low)',
    'AML Status': 'Cleared',
    'Sanctions Check': 'Passed',
    'PEP Screening': 'Not Applicable',
    'Geographic Risk': 'Low',
    'Transaction Velocity': 'Normal',
    'Account Age': '5+ years',
    'Previous Flags': 'None',
  };

  const complianceInfo = {
    'Regulatory Framework': 'RBI Guidelines 2023',
    'Reporting Status': 'CTR Filed',
    'Tax Implications': 'TDS Applicable',
    'Documentation': 'Complete',
    'Audit Trail': 'Maintained',
    'Data Retention': '7 Years',
    'Privacy Compliance': 'GDPR Compliant',
    'Encryption Standard': 'AES-256',
  };

  return (
    <div className="max-w-6xl mx-auto p-6">
      {/* Header */}
      <div className="mb-6">
        <Link 
          to="/" 
          className="inline-flex items-center text-blue-600 hover:text-blue-700 mb-4 transition-colors"
        >
          <ArrowLeft className="w-4 h-4 mr-2" />
          Back to Results
        </Link>
        <div className="bg-white rounded-xl shadow-lg border border-gray-200 p-6">
          <div className="flex items-center justify-between mb-4">
            <h1 className="text-2xl font-bold text-gray-900">Transaction Details</h1>
            <div className="flex items-center space-x-2">
              <span className="px-3 py-1 rounded-full bg-green-100 text-green-700 text-sm font-medium">
                {transaction.status}
              </span>
              <span className="px-3 py-1 rounded-full bg-blue-100 text-blue-700 text-sm font-medium">
                {transaction.type}
              </span>
            </div>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <div>
              <p className="text-sm text-gray-500">Transaction ID</p>
              <p className="font-mono text-sm text-gray-900">{transaction.id}</p>
            </div>
            <div>
              <p className="text-sm text-gray-500">Amount</p>
              <p className="text-2xl font-bold text-gray-900">₹{transaction.amount.toLocaleString()}</p>
            </div>
            <div>
              <p className="text-sm text-gray-500">Date</p>
              <p className="text-gray-900">{transaction.date}</p>
            </div>
          </div>
        </div>
      </div>

      {/* AI Summary */}
      <MarkdownSummary content={aiSummary} />

      {/* Payment Events */}
      <PaymentEvents events={paymentEvents} />

      {/* Info Sections Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <InfoSection
          title="Payment Party Information"
          icon={<Users className="w-5 h-5" />}
          data={paymentPartyInfo}
          iconColor="text-blue-600"
          bgColor="from-blue-50 to-cyan-50"
        />
        
        <InfoSection
          title="Remittance Details"
          icon={<CreditCard className="w-5 h-5" />}
          data={remittanceInfo}
          iconColor="text-purple-600"
          bgColor="from-purple-50 to-pink-50"
        />
        
        <InfoSection
          title="Risk & Compliance"
          icon={<Zap className="w-5 h-5" />}
          data={riskInfo}
          iconColor="text-green-600"
          bgColor="from-green-50 to-emerald-50"
        />
        
        <InfoSection
          title="Regulatory Compliance"
          icon={<Building className="w-5 h-5" />}
          data={complianceInfo}
          iconColor="text-orange-600"
          bgColor="from-orange-50 to-yellow-50"
        />
      </div>
    </div>
  );
};

export default TransactionDetails;